name: Copy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa
        ssh-keyscan -t rsa 68.183.88.61 >> ~/.ssh/known_hosts

    - name: Copy file to remote server
      run: |
        ssh -i  ~/.ssh/id_rsa 68.183.88.61 "hostname"
